source 'https://github.com/CocoaPods/Specs.git'  #官方仓库的地址
use_frameworks!

target 'XMGFMMain_Example' do
  pod 'XMGFMMain', :path => '../'

  target 'XMGFMMain_Tests' do
    inherit! :search_paths

    
  end
end
